//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::channel_roles::Entity as ChannelRoles;
pub use super::owners::Entity as Owners;
pub use super::roles::Entity as Roles;
pub use super::user_roles::Entity as UserRoles;
